all:
	g++ 1.cpp -I /data/data/com.termux/files/home/../usr/include/qt/QtWidgets/ -I /data/data/com.termux/files/home/../usr/include/qt/QtCore/ -I /data/data/com.termux/files/home/../usr/include/qt/QtGui/ -I /data/data/com.termux/files/home/../usr/include/qt/ -lQt5Core -lQt5Gui -lQt5Widgets -std=c++11
